print('====== DESAFIO 02 ======')
print('Insira sua data de nascimento.')
dia = input('Dia = ')
mes = input('Mes = ')
ano = input('Ano = ')
print('Você nasceu no dia', dia, 'de', mes, 'de', ano, '. Correto?')
