print('======DESAFIO 04======')
print('Calculo delta')
a = float(input('Digite o valor de a: '))
b = float(input('Digite o valor de b: '))
c = float(input('Digite o valor de c: '))
d = (b**2 - 4*a*c)
print('O valor de delata é: {}'.format(d))