/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


package progforca;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Santos
 */
public class ProgForca extends javax.swing.JFrame {

    private String bold = "";
    Funcao f = new Funcao();
    


    /**
     * Creates new form ProgForca
     * @throws java.io.IOException
     */
    public ProgForca() throws IOException {
        initComponents();
        f.Criar();    

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        painelForca = new javax.swing.JPanel();
        lblImagem = new javax.swing.JLabel();
        lblResult = new javax.swing.JLabel();
        lblTem = new javax.swing.JLabel();
        btnL = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        painelPalavra = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtLetra = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        lblPalavra = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblNtem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/forca01.JPG"))); // NOI18N

        btnL.setText("Outra Letra");
        btnL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelForcaLayout = new javax.swing.GroupLayout(painelForca);
        painelForca.setLayout(painelForcaLayout);
        painelForcaLayout.setHorizontalGroup(
            painelForcaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelForcaLayout.createSequentialGroup()
                .addGroup(painelForcaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelForcaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTem, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelForcaLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(lblImagem))
                    .addGroup(painelForcaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblResult, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelForcaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnL)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelForcaLayout.setVerticalGroup(
            painelForcaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelForcaLayout.createSequentialGroup()
                .addComponent(lblImagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblResult, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTem, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnL))
        );

        jLabel1.setText("Jogo da Forca");

        jLabel2.setText("Digite uma letra:");

        txtLetra.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtLetra.setDropMode(javax.swing.DropMode.INSERT);
        txtLetra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtLetraKeyPressed(evt);
            }
        });

        jLabel5.setText("A palavra é:");

        jLabel7.setText("Não contém:");

        lblNtem.setText(" ");

        javax.swing.GroupLayout painelPalavraLayout = new javax.swing.GroupLayout(painelPalavra);
        painelPalavra.setLayout(painelPalavraLayout);
        painelPalavraLayout.setHorizontalGroup(
            painelPalavraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPalavraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelPalavraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(painelPalavraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNtem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPalavra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(painelPalavraLayout.createSequentialGroup()
                        .addComponent(txtLetra, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 102, Short.MAX_VALUE))))
        );
        painelPalavraLayout.setVerticalGroup(
            painelPalavraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPalavraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelPalavraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtLetra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelPalavraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(lblPalavra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelPalavraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblNtem))
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(painelPalavra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(painelForca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(painelForca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelPalavra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void txtLetraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLetraKeyPressed
        // TODO add your handling code here:
        String b = txtLetra.getText();
    }//GEN-LAST:event_txtLetraKeyPressed

    private void btnLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLActionPerformed
        // TODO add your handling code here:
        //aqui



        //String b = txtL.getValue().toString();
        
        if ((!b.equals(""))&&(!b.equals(bold))){
            System.out.println("b " + b);
            f.Jogo(b,bold);
            System.out.println("bold " + bold);
            
            int i;
            int j = 0;
            for(i = 0; i < f.x[j]; i ++)//for de zero ate a quantidade de letras da palavra
            {
                if(bold.charAt(0) == f.palavra[i][j])//se a letra digitada for igual a uma das letras da palavra
                {
                    if(f.confere[i][j] != bold.charAt(0))//para nao repitir acerto de uma mesma letra.
                    {
                        f.confere[i][j] = bold.charAt(0);//o vetor de caracteres recebera na mesma posicao a letra digitada
                        f.contx +=1;//contador de acertos por tentativa recebe o valor dele mais um
                        f.contf +=1;//contador acertos total recebe o valor dele mais um.
                        System.out.println("confere " + i);
                    }//fim do se
                }//fim do se
            }//fim do for
            this.bold = b;
            
            switch(f.cont){
                case 2:
                    lblImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/forca02.JPG")));
                    break;
                case 3:
                    lblImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/forca03.JPG")));
                    break;
                case 4:
                    lblImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/forca04.JPG")));
                    break;
                case 5:
                    lblImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/forca05.JPG")));
                    break;
                case 6:
                    lblImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/forca06.JPG")));
                    break;
                case 7:
                    lblImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/forca07.JPG")));
                    lblResult.setText("Você perdeu!");
                    break;
                default:
                    lblImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/forca01.JPG")));
            }
        
        }
    }//GEN-LAST:event_btnLActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
              
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
                    
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProgForca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new ProgForca().setVisible(true);
            } catch (IOException ex) {
                Logger.getLogger(ProgForca.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnL;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblImagem;
    private javax.swing.JLabel lblNtem;
    private javax.swing.JLabel lblPalavra;
    private javax.swing.JLabel lblResult;
    private javax.swing.JLabel lblTem;
    private javax.swing.JPanel painelForca;
    private javax.swing.JPanel painelPalavra;
    public javax.swing.JTextField txtLetra;
    // End of variables declaration//GEN-END:variables
}
